theme: jekyll-theme-minimal
title: Abakoda <span class="baybayin>ᜀᜊᜃᜓᜓᜇ</span>
description: Abakoda is a series of online programming contests targeted to those who know a little bit of programming, but who have little to no experience in programming contests.
logo: images/logo.svg
